{
 "title": "Arena",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "VM total run queue lengths total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vm_total_run_queue_lengths_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM total run queue lengths IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "vm_total_run_queue_lengths_io", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "VM total run queue lengths CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "vm_total_run_queue_lengths_cpu", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Game tick duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(le) (arena_game_tick_duration_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Game count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arena_game_count", "legendFormat": "__auto" }
   ]
  }
 ]
}