[package]
name = "astarnative"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "astarnative"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.31.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
